# Generated by Django 4.1.7 on 2023-02-16 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_alter_movieorder_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movieorder",
            old_name="title",
            new_name="movie",
        ),
        migrations.RenameField(
            model_name="movieorder",
            old_name="buyed_by",
            new_name="user",
        ),
    ]
