# Generated by Django 4.1.7 on 2023-02-17 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_rename_title_movieorder_movie_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="added_by",
            new_name="user",
        ),
    ]
