# Generated by Django 4.1.7 on 2023-02-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_rename_added_by_movie_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="synopsis",
            field=models.TextField(default=None, null=True),
        ),
    ]
